### ISSUE TITLE
Refactor suggestion: rename classes

### ISSUE THREAD

**Issue by mBelisarius** [ThiagoDSMarcelino/BogoLib#4]
All the code belongs to the namespace BogoLib, therefore the classes don't need to start with 'Bogo'. For instance, the class `BogoLib.BogoMathF` would be refactored to `BogoLib.MathF`.

**Comment by ThiagoDSMarcelino** [comment]
Thanks for the suggestion, refactoring done for better readability and understanding of using the bogo library
